stages:
  - deploy

pages:
  stage: deploy
  image: harbor.lingjie.tech/library/builder:1.3
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  script:
    - yarn install
    - yarn docs:build
    - rm -rf dist/CNAME
    - mv dist public


